<?php

namespace ExampleBundle\Repository;

/**
 * ProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActives()
    {
        return $this->getAllActivesQueryBuilder()->getQuery()->getResult();
    }

    public function getAllActivesQueryBuilder()
    {
        return $this->createQueryBuilder('pc')
            ->where('pc.active = :active')
            ->setParameter('active', false);
    }
}
