<?php

namespace AppBundle\Repository;

/**
 * CategoriaFPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaFPRepository extends \Doctrine\ORM\EntityRepository
{
}
