<?php

namespace AppBundle\Repository;
use AppBundle\Entity\FinanzasPersonales;

/**
 * FinanzasPersonalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinanzasPersonalesRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Guardar datos
     * @param FinanzasPersonales $finanzasPersonales
     * @param bool $flush
     */
    public function save(FinanzasPersonales $finanzasPersonales, $flush = true)
    {
        $this->_em->persist($finanzasPersonales);
        $flush && $this->_em->flush();
    }
}
