<?php

namespace AppBundle\Repository;

/**
 * TipoFPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoFPRepository extends \Doctrine\ORM\EntityRepository
{
}
