# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
imports:
    - { resource: services/repositories.yml }
    - { resource: services/admin.yml}

services:
    app.message_generator:
        class: AppBundle\Service\MessageGenerator
        calls:
            - method: setLogger
              arguments:
                - '@logger'

    app.image_type_extension:
            class: AppBundle\Form\Extension\ImageTypeExtension
            tags:
                - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }



    #app.exception_listener:
    #    class: AppBundle\EventListener\ExceptionListener
    #    tags:
    #        - { name: kernel.event_listener, event: kernel.exception }

    #app.exception_subscriber:
    #    class: AppBundle\EventSubcriber\ExceptionSubscriber
    #    tags:
    #        - { name: kernel.event_subscriber }

    #app.listener.disable_active_product_category_filter:
    #  class: AppBundle\EventListener\DisableProductCategoryFilterListener
    #  arguments:
    #    - "@doctrine.orm.entity_manager"
    #    - "@security.authorization_checker"
    #  tags:
    #    - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    #Ejercicio Voter
    #product_voter:
    #    class:      AppBundle\Security\ProductVoter
    #    arguments: ['@security.access.decision_manager']
    #    public:     false
    #    tags:
    #       - { name: security.voter }

    #app.gateway.product:
    #  class: ExampleBundle\Gateway\ProductGateway
    #  arguments: ["@doctrine.orm.entity_manager"]

    #app.twig.extension.boolean_to_string:
    #  class: ExampleBundle\Twig\Extension\BooleanToStringExtension
    #  arguments:
    #    - "@translator"
    #  public: false
    #  tags:
    #    - { name: twig.extension}

    #app.listener.hola_mundo_logger:
    #  class: ExampleBundle\EventListener\HolaMundoLogger
    #  arguments: ["@logger"]
    #  tags:
    #    - { name: kernel.event_listener, event: kernel.request, method: agregarMensajeAlLoger }

    #app.listener.disable_active_product_category_filter:
    #  class: ExampleBundle\EventListener\DisableProductCategoryFilterListener
    #  arguments:
    #    - "@doctrine.orm.entity_manager"
    #    - "@security.authorization_checker"
    #  tags:
    #    - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }